### ISSUE TITLE
OnReady vars null on initial enter state

### ISSUE THREAD

**Issue by Red3Tango** [derkork/godot-statecharts#28] opened 2023-08-31 02:45 UTC
Using vars that are set with `@onready` (or in `_ready()`) are still unset when the Initial State is first Entered.
Only workaround I have found, for nodes use `$Node/Path` or `get_node()`. For dynamic vars, would need to be hard-coded.

I have not found an elegant way around this to "fix", and there may not be. A note or warning may be nice about the load order of when in runs the initial state enter signal.

**Comment by derkork** [comment] 2023-08-31 14:41
I think this is caused by the recent change that ensures that state changes happen in the same frame. It could be fixed by delaying entering the initial state of the state chart by one frame, to ensure that the full tree is ready.  

I'll build a new release with this change as i think this makes more sense than the current implementation but I will not be able to do it today. As a temporary workaround you can change this line in `state_chart.gd` which should delay the state entering by one frame:


![image](https://github.com/derkork/godot-statecharts/assets/327257/774e68e9-08be-4471-ba5e-4e4a0b4710ce)

**Comment by Red3Tango** [comment] 2023-08-31 15:19
I always forget that `call_deferred()` exists. Tested and can confirm this works.

**Closed** 2023-09-05 06:45 UTC

**Comment by derkork** [comment] 2023-09-05 06:50
Released 0.4.3 which has the fix built-in.
