### ISSUE TITLE
StateCharts platformer demo animation bug

### ISSUE THREAD

**Issue by jch02140** [derkork/godot-statecharts#33] opened 2023-09-12 21:37 UTC
I am not sure if it is due to my version of GoDot used. I am using GoDot 4.1.1. 

When I open the platformer demo that comes with the tool and try to run it, everything seems to work fine except when you do a double jump. The character is stuck in the spinning animation but the state in the debug box seems to be correctly displaying the states.

**Comment by derkork** [comment] 2023-09-13 04:56
It would seem that the animation is set to loop endlessly, which would explain why the character is spinning forever. Interestingly this doesn't seem to be an issue in 4.0, but I can reproduce it in 4.1. I have changed the animation to not loop and that seems to do the trick in 4.1 as well.

**Comment by derkork** [comment] 2023-09-13 05:00
Hmm no it's still not right , the animation is not aborted when the frog lands. Got to dig a bit deeper on this one.

**Comment by derkork** [comment] 2023-09-13 05:27
Now I can't reproduce it anymore, this animation stuff is really finicky. In any case the main problem should be fixed now, if you find a way of reproducing a roll after a double jump I'd be interested. Thanks a lot!

**Closed by derkork** 2023-09-13 05:27 UTC
