### ISSUE TITLE
Double _on_enter() due to compound_state

### ISSUE THREAD

**Issue by Remi123** [derkork/godot-statecharts#1] opened 2023-04-06 04:37 UTC
It took me a while to reproduce but I found out that some architecture can trigger on_enter and on_exit twice.

Small explanation of my nodes : 
I have a character that move in the Move state, then once I click it goes into Jump state and immediatly transition to a Falling state.
I've connected the `on_enter()` function of the Move and Falling state to a function that print respectively `Move` and  `Falling enter ` with the timestamp.

With this setup : 
![image](https://user-images.githubusercontent.com/16803994/230270146-8bc2421c-e66e-41d4-958e-7146db343bed.png)
Produce this result : 
![image](https://user-images.githubusercontent.com/16803994/230270250-8a5bf7c5-e47f-4394-a4fa-5b77c2c813f3.png)

However this architecture :
![image](https://user-images.githubusercontent.com/16803994/230272226-eb2cfec1-134b-4f6f-a2a9-db74832b0930.png)
Airborne also print its name on enter
Produce this result : 
![image](https://user-images.githubusercontent.com/16803994/230272172-ae18801d-d1f0-41ca-a5a8-9ffb65348dbd.png)

During transition, it seems that compoundstate trigger the on_enter() and on_exit of his children if it's the target node. I've looked into  the reference statechart.io website to see if it's an intended behavior, but didn't find any. I believe this is unintended behavior.

However I'm not familiar enough with the code to know why the root compoundstate isn't affected.

Thank you

**Comment by derkork** [comment] 2023-04-06 07:27
Hey Remi123, thanks a lot for reporting this. It is indeed not intended behaviour. The "Airborne" state will activate it's default child state when entered. However since this is part of a transition it actually should not do this. I have added a fix for this and will release an update with it. I have also added some improvements to the state chart debugger so it can track state change events for you without you having to litter your code with print statements:

![image](https://user-images.githubusercontent.com/327257/230304662-aca9e77c-333b-426a-94ef-308370d0b1b7.png)

In the screenshot you can now also see the fixed behaviour, when _AA_ transitions to _ABA_ , _ABA_ will only be activated once.

**Closed** 2023-04-06 14:17 UTC
